# https://docs.travis-ci.com/user/languages/r
# https://ropensci.org/blog/2016/07/12/travis-osx
# https://docs.travis-ci.com/user/ci-environment/
# https://docs.travis-ci.com/user/languages/r
# https://docs.travis-ci.com/user/build-matrix/
# https://docs.travis-ci.com/user/languages/cpp/

language: R
cache: packages
warnings_are_errors: false
pandoc: false
latex: false
# can/will also do these with environment variables. I do want a vignette build on travis on at least one platform
r_build_args: --no-build-vignettes --no-manual --resave-data=no
r_check_args: --no-build-vignettes --no-vignettes --ignore-vignettes --no-codoc --no-manual
os:
    - linux
    - osx

      #dist:

r:
    - devel
    - release
    - oldrel

r_binary_packages:
    - Rcpp
    - RcppEigen
    - rappdirs
    - testthat

env:
    global:
        # see also travis-global environment file
        - ICD_SHUTUP=true
        - ICD_MINI_BENCH=false
        - ICD_COVERAGE=false
        - ICD_TEST_SLOW=false
        - ICD_DATA_OFFLINE=true
        - ICD_DATA_INTERACT=false

    before_install:
        - tools/dump-env.sh;
        - mkdir -p ~/.R;
        - echo '^vignettes\/.*-vignette\.Rnw$' >> .Rbuildignore;
        - tools/DESCRIPTION-minimalize.sh;

    after_success:
        - tools/dump-env.sh 
        - if [[ "$ICD_MINI_BENCH" == "true" ]]; then
          cd benchmarks/icd-JSS3447-replication;
          eval "make bench3";
          eval "make replmat";
          cd ../..;
          fi

    after_failure:
        - tools/dump-env.sh;

    before_script:
        - tools/dump-env.sh; 

    jobs:
        fast_finish: true
        allow_failures:
            - os: osx

              notifications:
                  email:
                      on_success: change
                      on_failure: always
