# https://docs.travis-ci.com/user/languages/r
language: r
# https://ropensci.org/blog/2016/07/12/travis-osx
# https://docs.travis-ci.com/user/ci-environment/

# for RcppEigen to compile, (but disable if brew gcc on mac to avoid conflict)
# fortran: true # set explicitly in each stanza? but not recognized by an "include" group.

# may need this for clang:
# export LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH
#
# See this for more recent compiler support than old defaults:
# https://docs.travis-ci.com/user/languages/c/
#
# and
#
# https://docs.travis-ci.com/user/languages/cpp/

# assert the defaults for os and dist - will add macos and bionic etc. later
os:
 - linux
 - macos

dist:
# - xenial
 - bionic

cache:
  - packages
  - ccache

r:
  - release
  - devel

# definitely not required, but may give better travis reporting
# use_devtools: true

#addons:
#  apt:
#    packages:
#      - valgrind # when I do do this (probably too slow for travis anyway, then just put the apt addon in the specific build)

repos:
  CRAN: https://cloud.r-project.org
# by default, DON'T do --as-cran, as it stops us using environment variables
# that conflict. Instead, state approximate CRAN check environment variables explicitly. Blank is ignored? Try a non-empty innocuous argument.
#r_check_args: '--timings'
# default is true, which I would like; but false for travis-tricky platform/toolchain combos eventually
warnings_are_errors: false
# this will be a long list if all data extraction and devleopment dependencies are included. Will look for a way to slim this, e.g. although I do use readxl, this is not necessarily tested every time.
# N.b., these versions may be a bit older, and especially for compiled packages, they may need to be rebuilt anyway against Rcpp with the chosen compiler. MacOS builds are from source anyway, so it may be okay.
# These come from: https://launchpad.net/~marutter/+archive/ubuntu/c2d4u3.5 (which has the LTS versions). Another PPA has each Ubuntu release binaries.
# These (should) be installed in /usr/lib/R/site-library/ which is NOT on the default library search path in travis! The default paths in current travis look like:
# "/home/travis/R/Library", "/usr/local/lib/R/site-library", "/home/travis/R-bin/lib/R/library"
r_binary_packages:
  - Rcpp
  - RcppEigen
  - rappdirs
  - testthat

env:
  global:
    # don't know whether this is needed:
#    - HOMEBREW_NO_INSTALL_CLEANUP=1
    # avoid the default install script upgrading packages we already installed from r-cran-xxx apt
#    - R_REMOTES_UPGRADE=never
    - ICD_MINIBENCH=false
    - ICD_JUSTTEST=true

# this is great, but brew doesn't link to path by default: either brew link --force (or --overwrite?), or add to $PATH
brew_packages:
  - gcc

before_install:
  - mkdir -p ~/.R;
  - pwd;
  # https://stackoverflow.com/questions/31879011/r-cant-find-packages-installed-by-travis
  # - mkdir -p "$HOME/R.icd.lib"
  - if [[ -f /etc/.Renviron ]]; then cat /etc/.Renviron; fi
  # put the installed packages' path in the environment!
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      echo R_LIBS="/usr/lib/R/site-library/:/home/travis/R/Library:usr/local/lib/R/site-library:/home/travis/R-bin/lib/R/library" > ~/.Renviron;
      cp ~/.Renviron ~/.R/check.Renviron;
      cp ~/.Renviron ~/.R/build.Renviron;
    fi;
  - cat tools/env/travis-global >> ~/.R/check.Renviron;
  - cat tools/env/travis-global >> ~/.R/build.Renviron;
  # TRAVIS_R_VERSION_STRING is one ofldrel, release or devel per https://docs.travis-ci.com/user/languages/r#configuration-options
  - if [[ "$TRAVIS_R_VERSION_STRING" == devel ]]; then cat tools/mk/travis-debug.mk >> ~/.R/Makevars; fi;
    # TODO add --enable-icd-* configure args to help debug
  # ignore the stubs for the pre-built vignettes, as the latex environments on travis are heterogeneous!
  - echo '^vignettes\/.*-vignette\.Rnw$' >> .Rbuildignore
  # we do not need to install a ton of heavy dependencies just to run tests. travis installs suggests by default. This will cause warnings in the CRAN check, of course.
  - >
   if [[ "$ICD_JUSTTEST" == "true" ]]; then
     sed -e '/^Suggests:/,/LinkingTo:/c\LinkingTo:\\' DESCRIPTION |
     sed -e '/LinkingTo:/iSuggests:\n    testthat\n    magrittr' | tee DESCRIPTION.justtest
     mv DESCRIPTION.justtest DESCRIPTION
   fi
  - cat tools/mk/travis-nowarn.mk >> ~/.R/Makevars
  # https://github.com/Homebrew/homebrew-core/blob/master/Formula/gcc.rb
  # I think PKG_CXX etc only needed in environment, or Makevars in the package itself? not ~/.R/Makevars.
  # openblas may need brew linking. may be best NOT to overwrite gfortran?
  # the R travis module has its own brew_packages command. If we are using Xcode toolchain, we can use the R module command 'disable_homebrew'
  #  - export HOMEBREW_NO_INSTALL_CLEANUP=1 && if [[ "$(uname -s)" = 'Darwin' ]] && [[ $ICD_USE_XCODE_CLANG != 'true' ]]; then
  #      brew upgrade ;
  #      brew install gcc ;
  #      brew link --overwrite gcc ;
  #      cat tools/mk/travis-macos.mk  >> ~/.R/Makevars ;
  #      Rscript -e 'install.packages("Rcpp", type = "source")' ;
  #    fi
  - pwd
  - if [[ -f ~/.R/Makevars ]]; then cat ~/.R/Makevars; fi
  - if [[ -f .Rbuildignore ]]; then cat .Rbuildignore; fi
  - if [[ -f /etc/.Renviron ]]; then cat /etc/.Renviron; fi
  - if [[ -f ~/.Renviron ]]; then cat ~/.Renviron; fi
  - Rscript -e '.libPaths(); getOption("repos")'

jobs:
  fast_finish: true
  include:
  - r: devel
    dist: bionic
    # note that the default compilers are quite far behind, e.g. bionic is only gcc 7 by default. See:
    # https://docs.travis-ci.com/user/languages/c/#choosing-compilers-to-test-against
    compiler: gcc
    env:
      - ICD_MINI_BENCH=true
  - r: release
    compiler: clang
    dist: bionic
    env:
      - ICD_MINI_BENCH=true
  - r: release
    compiler: gcc
    latex: false
    r_build_args: --no-build-vignettes --no-manual --resave-data=no
    r_check_args: --no-build-vignettes --no-vignettes --ignore-vignettes --no-codoc --no-manual
    env:
    - ICD_JUSTTEST=true
    - ICD_COVERAGE=true
    - ICD_MINI_BENCH=false
    - ICD_TEST_SLOW=true
  - r: oldrel
    compiler: gcc
    pandoc: false
    latex: false
    r_build_args: --no-build-vignettes --no-manual --resave-data=no
    r_check_args: --no-build-vignettes --no-vignettes --ignore-vignettes --no-codoc --no-manual
    env:
    - ICD_JUSTTEST=true
    #--install-args='--configure-args=--disable-openmp'
  # MacOS: https://docs.travis-ci.com/user/languages/c/#gcc-on-macos
  - r: release
    os: osx
    # xcode image is needed so things like _stdio.h are available to homebrew gcc
    osx_image: xcode10.3
    disable_homebrew: false
    addons:
      homebrew:
        packages:
          - gcc
          - checkbashisms
    env:
      - ICD_MINI_BENCH=true
  - r: devel
    os: osx
    # xcode image is needed so things like _stdio.h are available to homebrew gcc
    osx_image: xcode10.3
    disable_homebrew: false
    addons:
      homebrew:
        packages:
          - gcc
          - checkbashisms
  - r: devel
    os: osx
    disable_homebrew: true
    #env: ICD_USE_XCODE_CLANG=true
  - r: devel
    os: osx
    pandoc: false
    latex: false
    r_build_args: --no-build-vignettes --no-manual --resave-data=no
    r_check_args: --no-build-vignettes --no-vignettes --ignore-vignettes --no-codoc --no-manual
    env:
    - ICD_JUSTTEST=true
        #- ICD_USE_XCODE_CLANG=true
    - ICD_MINI_BENCH=true
  - r: release
    os: osx
    pandoc: false
    latex: false
    r_build_args: --no-build-vignettes --no-manual --resave-data=no
    r_check_args: --no-build-vignettes --no-vignettes --ignore-vignettes --no-codoc --no-manual
    env:
    - ICD_JUSTTEST=true
        #- ICD_USE_XCODE_CLANG=true
    - ICD_MINI_BENCH=true
 #  - r: release
 #    arch: arm64
 #    # linux assumes amd64 in current default R travis
 #    pandoc: false
 #    latex: false
 #    r_build_args: --no-build-vignettes --no-manual --resave-data=no
 #    r_check_args: --no-build-vignettes --no-vignettes --ignore-vignettes --no-codoc --no-manual
 #    env:
 #    - ICD_MINI_BENCH=true
 #    - ICD_TEST_SLOW=true
  allow_failures:
  # allow any osx to fail for now: error prone tool chains
  - os: osx
  - r: oldrel
    # if these things are not matched exactly to the job, or top-level environment, etc., this won't allow failure?
  - env: ICD_JUSTTEST=true
  - env: ICD_COVERAGE=true # probably won't work to allow failure

before_script:
# - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && command -v brew >/dev/null; then brew link --force gcc || true; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then command -v gcc && gcc --version || true; fi
 - echo "$LD_LIBRARY_PATH"
 - if [ x"$ICD_TEST_SLOW" = x"true" ]; then
     Rscript -e 'source("tools/split-tests.R"); testthat_split();';
   fi
 - printenv | sort

after_script:
 # should fail and stop travis with error if the quick benchmark code fails
 - if [[ "$ICD_MINI_BENCH" == "true" ]]; then
     cd benchmarks/icd-JSS3447-replication;
     eval "make bench3"
     eval "make replmat"
     cd ../..;
   fi

after_success:
 - if [[ "$ICD_COVERAGE" == "true" ]]; then
     Rscript -e 'source("tools/split-tests.R"); testthat_split();';
     Rscript -e 'install.packages("covr"); covr::codecov(quiet = FALSE)';
   fi

notifications:
  email:
    on_success: change
    on_failure: always
